services:

  # ─────────────────────────────────────────────────
  # PHP-FPM app
  # ─────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html               # your code
      - vendor_data:/var/www/html/vendor  # persist composer installs
    depends_on:
      - db
      - redis
    environment:
      XDEBUG_MODE: coverage
      XDEBUG_CONFIG: "client_host=host.docker.internal"

  # ─────────────────────────────────────────────────
  # Nginx → PHP-FPM
  # ─────────────────────────────────────────────────
  web:
    image: nginx:stable-alpine
    container_name: tms_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app

  # ─────────────────────────────────────────────────
  # Vite dev server (HMR)
  # ─────────────────────────────────────────────────
  node:
    image: node:18-alpine
    container_name: tms_node
    working_dir: /var/www/html
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - app

  # ─────────────────────────────────────────────────
  # MySQL
  # ─────────────────────────────────────────────────
  db:
    image: mysql:8.0
    container_name: tms_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tms
      MYSQL_USER: tms_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # ─────────────────────────────────────────────────
  # Redis (internal only)
  # ─────────────────────────────────────────────────
  redis:
    image: redis:6-alpine
    container_name: tms_redis
    # no host port

  # ─────────────────────────────────────────────────
  # phpMyAdmin
  # ─────────────────────────────────────────────────
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: tms_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: tms_user
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
  vendor_data: