services:

  # ─────────────────────────────────────────────────
  # PHP-FPM app
  # ─────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: php-app
    container_name: tms_app
    working_dir: /var/www/html
    entrypoint: ["/usr/local/bin/setup.sh"]
    command: ["php-fpm"]
    volumes:
      - ./src:/var/www/html
      - vendor_data:/var/www/html/vendor
    depends_on:
      - db
      - redis
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: tms
      DB_USERNAME: tms_user
      DB_PASSWORD: secret
      XDEBUG_MODE: coverage
      XDEBUG_CONFIG: "client_host=host.docker.internal"

  # ─────────────────────────────────────────────────
  # Nginx → PHP-FPM
  # ─────────────────────────────────────────────────
  web:
    image: nginx:stable-alpine
    container_name: tms_web
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
      - node

  # ─────────────────────────────────────────────────
  # Vite dev server (HMR)
  # ─────────────────────────────────────────────────
  node:
    image: node:18-alpine
    container_name: tms_node
    working_dir: /var/www/html/tms-frontend
    command: >
        sh -c "
          chown -R 1000:1000 /var/www/html/tms-frontend &&
          npm install &&
          npm run dev -- --host 0.0.0.0
        "
    volumes:
      - ./src/tms-frontend:/var/www/html/tms-frontend:delegated
      - tms_frontend_node_modules:/var/www/html/tms-frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - app

  # ─────────────────────────────────────────────────
  # MySQL
  # ─────────────────────────────────────────────────
  db:
    image: mysql:8.0
    container_name: tms_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tms
      MYSQL_USER: tms_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # ─────────────────────────────────────────────────
  # Redis (internal only)
  # ─────────────────────────────────────────────────
  redis:
    image: redis:6-alpine
    container_name: tms_redis
    # no host port

  # ─────────────────────────────────────────────────
  # phpMyAdmin
  # ─────────────────────────────────────────────────
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: tms_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: tms_user
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
  vendor_data:
  tms_frontend_node_modules: